### ISSUE TITLE
Does this work with OCLP 1.5.0+ and macOS distribution like Sonoma?

### ISSUE THREAD

**Issue by alediaz84** [Sjenja87/dGMUX_BKeys#6]
Hi! I'm currently trying to solve brightness not working on macOS Ventura with the gmuxbypass found at https://github.com/ayilm1/gMUXBypass (I've opened an [issue](https://github.com/ayilm1/gMUXBypass/issues/14)) and I was wondering if this solution works with macOS like Ventura, Sonoma, etc. when installing them with OCLP.

Thanks

**Comment by Wachenanggo** [comment]
it should work since its a hardware solution not software any OS it should work

**Comment by Sjenja87** [comment]
This is a hardware solution so should work on any OS, but not tested.

**Comment by alediaz84** [comment]
Thanks! Closing! If I ever have the chance to test the scenario I'll post updates.

**Comment by alediaz84** [comment]
Tested and brightness works fine.
